In [2]:
#connect to Google

from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)

In [6]:
#Build Payload

kw_list = ['surface', 'biomaterial']  #can have up to five terms in a list
pytrends.build_payload(kw_list, timeframe='2004-01-01 2018-12-31')

In [7]:
# Interest Over Time
interest_over_time_df = pytrends.interest_over_time()
interest_over_time_df

            surface  biomaterial  isPartial
date
2004-01-01       51            0      False
2004-02-01       56            0      False
2004-03-01       54            0      False
2004-04-01       52            0      False
2004-05-01       50            0      False
2004-06-01       46            0      False
2004-07-01       41            0      False
2004-08-01       41            0      False
2004-09-01       49            0      False
2004-10-01       47            0      False
2004-11-01       45            0      False
2004-12-01       43            0      False
2005-01-01       46            0      False
2005-02-01       47            0      False
2005-03-01       45            0      False
2005-04-01       45            0      False
2005-05-01       46            1      False
2005-06-01       40            0      False
2005-07-01       40            0      False
2005-08-01       37            0      False
2005-09-01       49            0      False
2005-10-01       50            0      False
2005-11-01       49            0      False
2005-12-01       42            0      False
2006-01-01       48            0      False
2006-02-01       51            0      False
2006-03-01       45            0      False
2006-04-01       45            0      False
2006-05-01       47            0      False
2006-06-01       39            0      False
...             ...          ...        ...
2016-07-01       50            0      False
2016-08-01       54            0      False
2016-09-01       67            0      False
2016-10-01       75            0      False
2016-11-01       79            0      False
2016-12-01       65            0      False
2017-01-01       65            0      False
2017-02-01       69            0      False
2017-03-01       69            0      False
2017-04-01       67            0      False
2017-05-01       74            0      False
2017-06-01       61            0      False
2017-07-01       53            0      False
2017-08-01       58            0      False
2017-09-01       64            0      False
2017-10-01       66            0      False
2017-11-01       71            0      False
2017-12-01       63            0      False
2018-01-01       62            0      False
2018-02-01       65            0      False
2018-03-01       65            0      False
2018-04-01       66            0      False
2018-05-01       65            0      False
2018-06-01       54            0      False
2018-07-01       56            0      False
2018-08-01       61            0      False
2018-09-01       66            0      False
2018-10-01       70            0      False
2018-11-01       73            0      False
2018-12-01       63            0      False

[180 rows x 3 columns]