In [2]:
import pandas as pd

In [33]:
df = pd.read_csv('../data/raw_data/all.csv')

C:\Users\lin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (2,6,56,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
df['PY'].value_counts()

2018.0    4356
2017.0    4194
2016.0    3938
2015.0    3669
2014.0    3537
2013.0    3155
2012.0    2827
2011.0    2522
2010.0    2397
2009.0    2022
2008.0    1850
2007.0    1673
2005.0    1326
2006.0    1145
2004.0     974
2003.0     830
2002.0     715
2001.0     587
2019.0     576
1999.0     493
1998.0     448
1997.0     376
1996.0     347
1995.0     294
1994.0     274
1993.0     216
1992.0     176
1991.0     163
1990.0      93
1988.0      55
1989.0      48
1985.0      38
1984.0      38
1983.0      33
1986.0      32
1987.0      30
1979.0      23
1982.0      22
1977.0      22
1981.0      21
1980.0      20
1976.0      16
1978.0      15
1975.0      14
1972.0      14
1974.0      12
1973.0       6
Name: PY, dtype: int64

In [12]:
start = 1973

In [32]:
df[df.PY.isin([i for i in range(start,start+4)])].PY.value_counts()

1976.0    16
1975.0    14
1974.0    12
1973.0     6
Name: PY, dtype: int64

In [54]:
for year in range(1973,2017):
    tmp = df[df.PY.isin([i for i in range(year,year+4)])]
    print('Processing {} to {}'.format(year,year+3))
    print(tmp.PY.value_counts())
    tmp.reset_index(drop=True,inplace=True)
    tmp.to_csv('../data/year/{}_to_{}.csv'.format(year,year+3),index=False)

Processing 1973 to 1976
1976.0    16
1975.0    14
1974.0    12
1973.0     6
Name: PY, dtype: int64
Processing 1974 to 1977
1977.0    22
1976.0    16
1975.0    14
1974.0    12
Name: PY, dtype: int64
Processing 1975 to 1978
1977.0    22
1976.0    16
1978.0    15
1975.0    14
Name: PY, dtype: int64
Processing 1976 to 1979
1979.0    23
1977.0    22
1976.0    16
1978.0    15
Name: PY, dtype: int64
Processing 1977 to 1980
1979.0    23
1977.0    22
1980.0    20
1978.0    15
Name: PY, dtype: int64
Processing 1978 to 1981
1979.0    23
1981.0    21
1980.0    20
1978.0    15
Name: PY, dtype: int64
Processing 1979 to 1982
1979.0    23
1982.0    22
1981.0    21
1980.0    20
Name: PY, dtype: int64
Processing 1980 to 1983
1983.0    33
1982.0    22
1981.0    21
1980.0    20
Name: PY, dtype: int64
Processing 1981 to 1984
1984.0    38
1983.0    33
1982.0    22
1981.0    21
Name: PY, dtype: int64
Processing 1982 to 1985
1984.0    38
1985.0    38
1983.0    33
1982.0    22
Name: PY, dtype: int64
Processing 1983 to 1986
1985.0    38
1984.0    38
1983.0    33
1986.0    32
Name: PY, dtype: int64
Processing 1984 to 1987
1985.0    38
1984.0    38
1986.0    32
1987.0    30
Name: PY, dtype: int64
Processing 1985 to 1988
1988.0    55
1985.0    38
1986.0    32
1987.0    30
Name: PY, dtype: int64
Processing 1986 to 1989
1988.0    55
1989.0    48
1986.0    32
1987.0    30
Name: PY, dtype: int64
Processing 1987 to 1990
1990.0    93
1988.0    55
1989.0    48
1987.0    30
Name: PY, dtype: int64
Processing 1988 to 1991
1991.0    163
1990.0     93
1988.0     55
1989.0     48
Name: PY, dtype: int64
Processing 1989 to 1992
1992.0    176
1991.0    163
1990.0     93
1989.0     48
Name: PY, dtype: int64
Processing 1990 to 1993
1993.0    216
1992.0    176
1991.0    163
1990.0     93
Name: PY, dtype: int64
Processing 1991 to 1994
1994.0    274
1993.0    216
1992.0    176
1991.0    163
Name: PY, dtype: int64
Processing 1992 to 1995
1995.0    294
1994.0    274
1993.0    216
1992.0    176
Name: PY, dtype: int64
Processing 1993 to 1996
1996.0    347
1995.0    294
1994.0    274
1993.0    216
Name: PY, dtype: int64
Processing 1994 to 1997
1997.0    376
1996.0    347
1995.0    294
1994.0    274
Name: PY, dtype: int64
Processing 1995 to 1998
1998.0    448
1997.0    376
1996.0    347
1995.0    294
Name: PY, dtype: int64
Processing 1996 to 1999
1999.0    493
1998.0    448
1997.0    376
1996.0    347
Name: PY, dtype: int64
Processing 1997 to 2000
1999.0    493
1998.0    448
1997.0    376
Name: PY, dtype: int64
Processing 1998 to 2001
2001.0    587
1999.0    493
1998.0    448
Name: PY, dtype: int64
Processing 1999 to 2002
2002.0    715
2001.0    587
1999.0    493
Name: PY, dtype: int64
Processing 2000 to 2003
2003.0    830
2002.0    715
2001.0    587
Name: PY, dtype: int64
Processing 2001 to 2004
2004.0    974
2003.0    830
2002.0    715
2001.0    587
Name: PY, dtype: int64
Processing 2002 to 2005
2005.0    1326
2004.0     974
2003.0     830
2002.0     715
Name: PY, dtype: int64
Processing 2003 to 2006
2005.0    1326
2006.0    1145
2004.0     974
2003.0     830
Name: PY, dtype: int64
Processing 2004 to 2007
2007.0    1673
2005.0    1326
2006.0    1145
2004.0     974
Name: PY, dtype: int64
Processing 2005 to 2008
2008.0    1850
2007.0    1673
2005.0    1326
2006.0    1145
Name: PY, dtype: int64
Processing 2006 to 2009
2009.0    2022
2008.0    1850
2007.0    1673
2006.0    1145
Name: PY, dtype: int64
Processing 2007 to 2010
2010.0    2397
2009.0    2022
2008.0    1850
2007.0    1673
Name: PY, dtype: int64
Processing 2008 to 2011
2011.0    2522
2010.0    2397
2009.0    2022
2008.0    1850
Name: PY, dtype: int64
Processing 2009 to 2012
2012.0    2827
2011.0    2522
2010.0    2397
2009.0    2022
Name: PY, dtype: int64
Processing 2010 to 2013
2013.0    3155
2012.0    2827
2011.0    2522
2010.0    2397
Name: PY, dtype: int64
Processing 2011 to 2014
2014.0    3537
2013.0    3155
2012.0    2827
2011.0    2522
Name: PY, dtype: int64
Processing 2012 to 2015
2015.0    3669
2014.0    3537
2013.0    3155
2012.0    2827
Name: PY, dtype: int64
Processing 2013 to 2016
2016.0    3938
2015.0    3669
2014.0    3537
2013.0    3155
Name: PY, dtype: int64
Processing 2014 to 2017
2017.0    4194
2016.0    3938
2015.0    3669
2014.0    3537
Name: PY, dtype: int64
Processing 2015 to 2018
2018.0    4356
2017.0    4194
2016.0    3938
2015.0    3669
Name: PY, dtype: int64
Processing 2016 to 2019
2018.0    4356
2017.0    4194
2016.0    3938
2019.0     576
Name: PY, dtype: int64